# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
theme: jekyll-theme-cayman
theme_version: 1.0.5

# Site settings
title:              Marcos Santiago
logo:               # Logo image URL
description:        Thoughts, Stories and Ideas
baseurl:            '' # The subpath of your site, e.g. /blog
url:                https://marcosstgo.github.io # The base hostname & protocol for your site
twitter:            https://twitter.com/warcos
facebook:           https://www.facebook.com/marcos.santiago
instagram:          https://www.instagram.com/m4rcos

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Marcos Santiago
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: https://secure.gravatar.com/avatar/2a77f5cd64c24789c14756af4754389f?s=150
    email:    hello@marcossantiago.com
    website:  http://marcossantiago.com
    github:   https://github.com/marcosstgo
    twitter:  https://twitter.com/warcos